export const myCustomLightTheme = {
  dark: false,
  colors: {
    primary: '#3C6939',
    surfaceTint: '#3C6939',
    onPrimary: '#FFFFFF',
    primaryContainer: '#BDF0B3',
    onPrimaryContainer: '#245023',
    secondary: '#53634F',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#D6E8CE',
    onSecondaryContainer: '#3B4B38',
    tertiary: '#38656A',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#BCEBF0',
    onTertiaryContainer: '#1E4D52',
    error: '#BA1A1A',
    onError: '#FFFFFF',
    errorContainer: '#FFDAD6',
    onErrorContainer: '#93000A',
    background: '#F7FBF1',
    onBackground: '#191D17',
    surface: '#F7FBF1',
    onSurface: '#191D17',
    surfaceVariant: '#DEE5D8',
    onSurfaceVariant: '#424940',
    outline: '#72796F',
    outlineVariant: '#C2C8BD',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#2D322B',
    inverseOnSurface: '#EFF2E9',
    inversePrimary: '#A1D399',
    primaryFixed: '#BDF0B3',
    onPrimaryFixed: '#002203',
    primaryFixedDim: '#A1D399',
    onPrimaryFixedVariant: '#245023',
    secondaryFixed: '#D6E8CE',
    onSecondaryFixed: '#111F0F',
    secondaryFixedDim: '#BACCB3',
    onSecondaryFixedVariant: '#3B4B38',
    tertiaryFixed: '#BCEBF0',
    onTertiaryFixed: '#002022',
    tertiaryFixedDim: '#A0CFD4',
    onTertiaryFixedVariant: '#1E4D52',
    surfaceDim: '#D8DBD2',
    surfaceBright: '#F7FBF1',
    surfaceContainerLowest: '#FFFFFF',
    surfaceContainerLow: '#F1F5EB',
    surfaceContainer: '#ECEFE6',
    surfaceContainerHigh: '#E6E9E0',
    surfaceContainerHighest: '#E0E4DB'
    // primary: '#904b3c',
    // 'surface-tint': '#904b3c',
    // 'on-primary': '#ffffff',
    // 'primary-container': '#ffdad3',
    // 'on-primary-container': '#733427',
    // secondary: '#775750',
    // 'on-secondary': '#ffffff',
    // 'secondary-container': '#ffdad3',
    // 'on-secondary-container': '#5d4539',
    // tertiary: '#6e5d2e',
    // 'on-tertiary': '#ffffff',
    // 'tertiary-container': '#f9e0a6',
    // 'on-tertiary-container': '#554519',
    // error: '#ba1a1a',
    // 'on-error': '#ffffff',
    // 'error-container': '#ffdad6',
    // 'on-error-container': '#93000a',
    // background: '#fff8f6',
    // 'on-background': '#231917',
    // surface: '#fff8f6',
    // 'on-surface': '#231917',
    // 'surface-variant': '#f5dcd9',
    // 'on-surface-variant': '#534340',
    // outline: '#85736f',
    // 'outline-variant': '#d8c2bd',
    // shadow: '#000000',
    // scrim: '#000000',
    // 'inverse-surface': '#392e2c',
    // 'inverse-on-surface': '#fff7e9',
    // 'inverse-primary': '#ffb4a4',
    // 'primary-fixed': '#ffdad3',
    // 'on-primary-fixed': '#3a0a03',
    // 'primary-fixed-dim': '#ffb4a4',
    // 'on-primary-fixed-variant': '#733427',
    // 'secondary-fixed': '#ffdad3',
    // 'on-secondary-fixed': '#2c150f',
    // 'secondary-fixed-dim': '#e7bdd1',
    // 'on-secondary-fixed-variant': '#5d4539',
    // 'tertiary-fixed': '#f9e0a6',
    // 'on-tertiary-fixed': '#241a00',
    // 'tertiary-fixed-dim': '#dbc38c',
    // 'on-tertiary-fixed-variant': '#554519',
    // 'surface-dim': '#e8d6d3',
    // 'surface-bright': '#fff8f6',
    // 'surface-container-lowest': '#ffffff',
    // 'surface-container-low': '#ffecde',
    // 'surface-container': '#fceea6',
    // 'surface-container-high': '#f7e4d1',
    // 'surface-container-highest': '#f1dfdb'
  },
  variables: {
    'border-color': '#000000',
    'border-opacity': 0.12,
    'high-emphasis-opacity': 0.87,
    'medium-emphasis-opacity': 0.6,
    'disabled-opacity': 0.38,
    'idle-opacity': 0.04,
    'hover-opacity': 0.04,
    'focus-opacity': 0.12,
    'selected-opacity': 0.08,
    'activated-opacity': 0.12,
    'pressed-opacity': 0.12,
    'dragged-opacity': 0.08,
    'theme-kbd': '#212529',
    'theme-on-kbd': '#FFFFFF',
    'theme-code': '#F5F5F5',
    'theme-on-code': '#000000'
  }
}
