name: buider et publier une version static sur Hostinger
on:
  push:
    branches: [ 'master' ]

jobs: 
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: git-checkout
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: |
          corepack enable
          yarn set version stable
          yarn install
      - name: Build
        run: yarn build
      - name: Copy .htaccess to build directory
        run: cp .htaccess ./dist/
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./dist/
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: build
        path: ./dist/
    - name: Deploy to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /public_html/
